baseURL = 'https://future-insight.blog/'
languageCode = 'en-us'
title = 'Future Insight'
theme = 'gokarna'
defaultContentLanguage = "en"
enableRobotsTXT = true

  # -----------------------------------------------------------
  #                 Default Parameters
  # -----------------------------------------------------------
[params]
    avatarURL = "/images/16.png"
    description = "Programming is not about typing, it's about thinking. - Rich Hickey"
    showPostsOnHomePage = "popular"
    togglePreviousAndNextButtons = "true"
    customHeadHTML = "<script>console.log('Any HTML')</script>"
    avatarSize = "size-l"
    socialIcons = [
      {name = "twitter", url = "https://twitter.com/abdul_rafay99"},
      {name = "linkedin", url = "https://www.linkedin.com/in/abdul-rafay1999/"},
       {name = "stackoverflow", url = "https://stackoverflow.com/users/13860632/abdul-rafay"},
      {name = "github", url = "https://github.com/rafay99-epic"},
    ]
    # pygmentsStyle = "monokai"
    metaKeywords = ["blog", "gokarna", "hugo"]
    search= true
    favicon = "/images/favicon.png"
    summaryLength = "10"
    code_copy_button = true 
    author = "Abdul Rafay"
    mainSections = ["posts", "projects","Authors"]
    pygmentsStyle = "catppuccin-frappe" 
    
  #---------------------------
  #     Google Analytics
  #---------------------------
    googleAnalytics="G-HSKPE7HLQL"

  #-----------------------------------------
  #               cookies
  #-----------------------------------------
  [params.cookies]
  enable = true
  expire_days = 2

  # -----------------------------------------------------------
  #                 Main Menu Parmeters
  # -----------------------------------------------------------
  
  # Home
  [[menu.main]]
    identifier = "home"
    url = "/"
    name = "Home"
    weight = 1
    pre = "<span data-feather='home'></span>"
  
  # Author
    [[menu.main]]
    identifier = "author"
    url = "https://rafay99.info"
    name = "Author"
    weight = 2
    pre = "<span data-feather='user'></span>"

  # Posts or Blogs
  [[menu.main]]
    identifier = "post"
    url = "/post/"
    name = "Posts"
    weight = 3
    pre = "<span data-feather='book'></span>"
    
    # #Projects 
    # [[menu.main]]
    # identifier = "page"
    # url = "/projects/"
    # name = "Projects"
    # weight = 4
    # pre = "<span data-feather='code'></span>"
  
  # Tage or Categories
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5
    pre = "<span data-feather='tag'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rafay99-epic"
    weight = 6
    pre = "<span data-feather='github'></span>"


# --------------------------------------
#   --- Markdown Config Section ---
# --------------------------------------

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

#-------------------------
#  Pre-Load images
#-------------------------
[params.preloader]
enable = true
preloader = "png" # use png, jpg, svg or gif format
