baseURL = 'https://rafay-blog.onrender.com'
languageCode = 'en-us'
title = 'Abdul Rafay Blogs'
theme = 'gokarna'
defaultContentLanguage = "en"
enableRobotsTXT = true

  # -----------------------------------------------------------
  #                 Default Parameters
  # -----------------------------------------------------------
[params]
    avatarURL = "/images/avatar.jpg"
    description = "Don't Comments bad code- rewrite it."
    showPostsOnHomePage = "popular"
    togglePreviousAndNextButtons = "true"
    customHeadHTML = "<script>console.log('Any HTML')</script>"
     socialIcons = [
      {name = "twitter", url = "https://twitter.com/abdul_rafay99"},
      {name = "linkedin", url = "https://www.linkedin.com/in/abdul-rafay1999/"},
       {name = "stackoverflow", url = "https://stackoverflow.com/users/13860632/abdul-rafay"},
      {name = "github", url = "https://github.com/rafay99-epic"},
    ]
    pygmentsStyle = "monokai"
    metaKeywords = ["blog", "gokarna", "hugo"]
    search= true
    favicon = "/images/favicon.jpg"
    summaryLength = "10"
    googleAnalytics = "G-HSKPE7HLQL"
  
  # -----------------------------------------------------------
  #                 Main Menu Parmeters
  # -----------------------------------------------------------
  [[menu.main]]
    identifier = "post"
    url = "/post/"
    name = "Posts"
    weight = 1
    pre = "<span data-feather='book'></span>"

  [[menu.main]]
    identifier = "home"
    url = "/"
    name = "Home"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    pre = "<span data-feather='tag'></span>"
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rafay99-epic"
    weight = 3
    pre = "<span data-feather='github'></span>"


# --------------------------------------
#   --- Markdown Config Section ---
# --------------------------------------

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true

[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false


