baseURL = 'https://futue-insight-test.onrender.com'
languageCode = 'en-us'
title = 'Future Insight'
theme = 'gokarna'
defaultContentLanguage = "en"
enableRobotsTXT = true

  # -----------------------------------------------------------
  #                 Default Parameters
  # -----------------------------------------------------------
[params]
    avatarURL = "/images/16.png"
    description = "Programming is not about typing, it's about thinking. - Rich Hickey"
    showPostsOnHomePage = "popular"
    togglePreviousAndNextButtons = "true"
    avatarSize = "size-l"
    socialIcons = [
      {name = "twitter", url = "https://twitter.com/abdul_rafay99"},
      {name = "linkedin", url = "https://www.linkedin.com/in/abdul-rafay1999/"},
       {name = "stackoverflow", url = "https://stackoverflow.com/users/13860632/abdul-rafay"},
      {name = "github", url = "https://github.com/rafay99-epic"},
      {name = "youtube", url = "https://www.youtube.com/"}
    ]
    footer = " by Future Insight"
    metaKeywords = ["blog", "gokarna", "hugo"]
    search= true
    favicon = ["/images/favicon/apple-touch-icon.png"]
    summaryLength = "10"
    code_copy_button = true 
    author = "Abdul Rafay"
    mainSections = ["posts", "projects","Authors"]
    pygmentsStyle = "catppuccin-frappe" 
  
  #---------------------------
  #     Google Analytics
  #---------------------------
    googleAnalytics="G-HSKPE7HLQL"

  #---------------------------
  # Website Output Format
  #---------------------------
  [outputs]
  home = ["HTML"]
 
  #-----------------------------------------
  #               cookies
  #-----------------------------------------
  [params.cookies]
    enable = true
    expire_days = 2

  # -----------------------------------------------------------
  #                 Main Menu Parmeters
  # -----------------------------------------------------------
  
  # Home
  [[menu.main]]
    identifier = "home"
    url = "/"
    name = "Home"
    weight = 1
    pre = "<span data-feather='home'></span>"
  
  # Author
    [[menu.main]]
    identifier = "author"
    url = "/author/"
    name = "Author"
    weight = 2
    pre = "<span data-feather='user'></span>"

  # Posts or Blogs
  [[menu.main]]
    identifier = "post"
    url = "/post/"
    name = "Posts"
    weight = 3
    pre = "<span data-feather='book'></span>"
    
  # Tage or Categories
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
    pre = "<span data-feather='tag'></span>"
  
  [[menu.main]]
    identifier="Privacy"
    name="Policy"
    url="/policy/"
    weight=5
    pre="<span data-feather='edit-3'></span>"
  
    # Projects
  [[menu.main]]
    identifier = "Contact"
    url = "/contact/"
    name = "Contact Me"
    weight = 6
    pre = "<span data-feather='send'></span>"
  
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rafay99-epic"
    weight = 7
    pre = "<span data-feather='github'></span>"


# --------------------------------------
#   --- Markdown Config Section ---
# --------------------------------------

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true

[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = true
      anchorLineNos = false
      hl_inline = false
      lineAnchors = ''
      noHl = false
      style = 'catppuccin-frappe'
      
  #-------------------------
  #  Pre-Load images
  #-------------------------
  [params.preloader]
  enable = true
  preloader = "png" # use png, jpg, svg or gif format
