#---------------------------------
# This is Development Config File
# Config File
#---------------------------------

baseURL = 'https://future-insight.blog'
languageCode = 'en-us'
title = 'Future Insight'
theme = 'gokarna'
defaultContentLanguage = "en"
enableRobotsTXT = true

  # -----------------------------------------------------------
  #                 Default Parameters
  # -----------------------------------------------------------
[params]
    avatarURL = "/images/16.png"
    description = "Programming is not about typing, it's about thinking. - Rich Hickey"
    showPostsOnHomePage = "popular"
    togglePreviousAndNextButtons = "true"
    avatarSize = "size-l"
    socialIcons = [
      {name = "twitter", url = "https://twitter.com/abdul_rafay99"},
      {name = "linkedin", url = "https://www.linkedin.com/in/abdul-rafay1999/"},
       {name = "stackoverflow", url = "https://stackoverflow.com/users/13860632/abdul-rafay"},
      {name = "github", url = "https://github.com/rafay99-epic"},
      {name = "youtube", url = "https://www.youtube.com/channel/UCw5ZdTiUJuMa2joLI089UnQ" }
    ]
    footer = " by Future Insight"
    metaKeywords = ["blog", "gokarna", "hugo"]
    search= true
    summaryLength = "10"
    code_copy_button = true 
    author = "Abdul Rafay"
    mainSections = ["posts", "projects","Authors","Service"]
    pygmentsStyle = "monokai" 
  
  #---------------------------
  #     Google Analytics
  #---------------------------
  googleAnalytics="G-HSKPE7HLQL"

  #---------------------------
  # Website Output Format
  #---------------------------
  [outputs]
  home = ["HTML"]
 
  #-----------------------------------------
  #               cookies
  #-----------------------------------------
  [params.cookies]
    enable = true
    expire_days = 2

  # -----------------------------------------------------------
  #                 Main Menu Parmeters
  # -----------------------------------------------------------
  
  [menu]
    # Home
    [[menu.main]]
      identifier = "home"
      url = "/"
      name = "Home"
      weight = 1
      pre = "<span data-feather='home'></span>"
    
    # Author
      [[menu.main]]
      identifier = "author"
      url = "/author/"
      name = "Author"
      weight = 2
      pre = "<span data-feather='user'></span>"

    # Posts or Blogs
    [[menu.main]]
      identifier = "post"
      url = "/post/"
      name = "Posts"
      weight = 3
      pre = "<span data-feather='book'></span>"
      
    # Tage or Categories
    [[menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 4
      pre = "<span data-feather='tag'></span>"
    
    # Service Page 
    [[menu.main]]
      identifier = "Services"
      name = "Services"
      url = "/services/"
      weight = 5
      pre = "<span data-feather='settings'></span>"

    # Github Link
    [[menu.main]]
      identifier = "github"
      url = "https://github.com/rafay99-epic"
      weight = 6
      pre = "<span data-feather='github'></span>"

  # Drop Down Menu Components
    [[menu.dropdown]]
      identifier = "About Us"
      url = "/About-Us/"
      name = "About Us"
      weight = 1
      Icon = "<span data-feather='info'></span>"

    [[menu.dropdown]]
      identifier = "Privacy Policy"
      url = "/policy/"
      name = "Privacy Policy"
      Icon = "<span data-feather='lock'></span>"
      weight = 2
    
    [[menu.dropdown]]
      identifier="Contact"
      url="/contact/"
      name="Contact US"
      weight=3
      Icon="<span data-feather='send'></span>"
    
    
# --------------------------------------
#   --- Markdown Config Section ---
# --------------------------------------

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true

[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = true
      anchorLineNos = false
      hl_inline = false
      lineAnchors = ''
      noHl = false
      style = 'monokai'
      
  #-------------------------
  #  Pre-Load images
  #-------------------------
  [params.preloader]
  enable = true
  preloader = "png" # use png, jpg, svg or gif format
